### ISSUE TITLE
Cannot run it

### ISSUE THREAD

**Issue by pistacchio** [inquisitiveSoft/MIDIAudioUnitExample#1]
Hi,
thanks for making this code public. I'm trying to run it to experiment with AUv3 MIDI programming. I managed to compile the plugin and run it on the iPad. When I try to run it standalone, I correctly get "The AudioUnit can be accessed from within a host audio app".

AUM discovers it, which is great (as you can see in the picture), but as soon as I click on it, it gives me a "MIDIAudioUnit failed" exception. Any help?

![image](https://user-images.githubusercontent.com/192145/111906346-63202580-8a50-11eb-9cea-aa504fc86a1c.png)

![image](https://user-images.githubusercontent.com/192145/111906351-674c4300-8a50-11eb-86cc-953a8f93c62a.png)

**Comment by pistacchio** [comment]
Update.
My error, I guess, was that I was trying to run MAUExampleApp instead of TransposeOctaveAudioUnit. Still it doesn't work, but the error is easier to find out. 
In Info.plist, the key `NSExtensionMainStoryboard` is set to "MainInterface". When running the plugin, it looks for the storyboard MainInterface that does not exist.

Any idea on how to solve this? Is part of the project missing?

**Comment by inquisitiveSoft** [comment]
Sorry for only seeing this now. I realised that a couple of commits on my computer that hadn't been pushed. It should be fixed now. I renamed the storyboard to TransposeOctave.storyboard, but hadn't updated that in the Info.plist.

Here's how it looks for me
![IMG_0001](https://user-images.githubusercontent.com/85400/114281409-1f5c8280-9a36-11eb-8271-0f403d1c3a59.PNG)

**Comment by inquisitiveSoft** [comment]
I'll close it for now. Feel free to reopen the issue if it's still a problem.
